---
title: "Lab 04 Ridge, Lasso, Elastic Net"
author: "Andy Jiang"
date: "2020-03-05"
output: html_document
---

### Load packages

```{r load-packages, message = FALSE, warning = FALSE}
library(tidyverse) 
library(tidymodels)
```

### Exercise 1

```{r split dataset into two}
music<- read.csv("music.csv",header = TRUE)

set.seed(7)

music_split <- initial_split(music, prop=0.5)
music_split

music_test <- testing(music_split)

music_train <- training(music_split)
```

As we can see, there are 73 variables in both the training and the testing dataset. Both have 250 observations each. 

### Exercise 2

```{r fitting linear model on lat}

lm_spec <-
  linear_reg()%>%
  set_engine(engine = "lm")
lm_spec
ols_train <- fit(lm_spec,
                 lat~.,
                 data = music_train)

ols_train
lat_pred<-ols_train %>%
  predict(new_data = music_test)%>%
  bind_cols(music_test)
lat_pred %>%
  rmse(truth=lat,estimate=.pred)


```

The testing root men squared error obtained is 18.616

### Exercise 3



```{r}
music_cv <- vfold_cv(music, 10)
ridge_spec <- linear_reg(penalty = 100, mixture = 0)%>%
  set_engine("glmnet")

rec <- recipe(lat ~., data = music)%>%
  step_scale(all_predictors())

results <- fit_resamples(lm_spec,
                         preprocessor = rec,
                         resamples = music_cv)

```












